### ISSUE TITLE
explore New Relic alert automation via API

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#104]
https://docs.newrelic.com/docs/apis/rest-api-v2/getting-started/introduction-new-relic-rest-api-v2

https://docs.newrelic.com/docs/apis/rest-api-v2/server-examples-v2/removing-server-index-v2

**Comment by glogiotatidis** [comment]
We can't use the API b/c we're on the Synthetics Lite account.

**Comment by glogiotatidis** [comment]
But there's [neres](https://github.com/glogiotatidis/neres/) and we can now script newrelic synthetics! \o/

**Comment by glogiotatidis** [comment]
@metadave should we mark this one done and create new cards to scripts our NR monitors?

**Comment by metadave** [comment]
@glogiotatidis neres looks excellent!!

New cards would be great. Thanks!

**Comment by glogiotatidis** [comment]
Filed #211
