### ISSUE TITLE
MDN demo deployment decommissioning

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#106]

**Comment by metadave** [comment]
in the virginia cluster, I see the following mdn related namespaces:

```
mdn-demo               Active    42d
mdn-demo-api           Active    1d
mdn-demo-content-exp   Active    5d
mdn-demo-example       Active    34d
mdn-demo-maint-mode    Active    8d
```
@jwhitlock was using `mdn-demo-content-exp`, I'm not about the rest.

**Comment by jwhitlock** [comment]
* ``mdn-demo`` - I guess this is the "Hey we can do it" deployment. I do not use. Eventually we'll want a master-tracking dev.developer.moz.works deployment
* ``mdn-demo-api`` - I don't use this
* ``mdn-demo-content-exp`` - We deployed this PR to production, 👍 to delete ( 👎 ?)
* ``mdn-demo-example`` - I don't use this
* ``mdn-demo-maint-mode`` - Code is merged, I think @escattone owns

**Comment by escattone** [comment]
@metadave @jwhitlock As far as I'm concerned, all of the resources in these kubernetes namespaces (and related YAML files) can be deleted.

**Comment by metadave** [comment]
@jwhitlock I'm unclear on your 👍 / 👎 comment, is it ok to delete that deployment?

**Comment by metadave** [comment]
The following Deis Workflow apps have been deleted:

- mdn-demo
- mdn-demo-api
- mdn-demo-example
- mdn-demo-maint-mode

**Comment by jwhitlock** [comment]
yes, you can delete the ``mdn-demo-content-exp`` demo. Is that 👍 to the idea of deletion, or 👎 to kill the gladiator? I will try to avoid ambiguous thumbs in the future.

**Comment by metadave** [comment]
`mdn-demo-content-exp` deleted.
