### ISSUE TITLE
public helm chart repo server

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#108]

**Comment by jgmize** [comment]
https://github.com/mozmar/cloudflare-datadog/issues/4#issuecomment-287086624

**Comment by so0k** [comment]
The alternative is now to use the freshly published CoreOS app registry https://coreos.com/blog/quay-application-registry-for-kubernetes.html

**Comment by jgmize** [comment]
I think the quay application registry makes more sense, so I'm going to close this out in favor of that. Thanks again @so0k!
