### ISSUE TITLE
deploy snippets service to tokyo cluster

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#116]
- [x] install cluster autoscaler
- [x] deis app + jenkins user permissions
- s3 bucket
  - [x] create s3 bucket with appropriate policies
  - [x] configure deis app to use s3 bucket
  - [ ] add s3 bucket to cloudfront distribution
    - [x] file bug with webops
      - [x] reference previous bug filed for virginia cluster
      - [x] cc @metadave @jgmize @glogiotatidis 
      - https://bugzilla.mozilla.org/show_bug.cgi?id=1351654
      - [ ] Configure `CDN_URL` when bug ^ gets fixed 
- RDS
  - [x] create tokyo instance
  - [x] configure replication
  - [x] configure deis app with new DATABASE_URL
- [x] create ELB via k8s annotations on new snippets-prod service
- [x] create redis elasticache instance
- [x] update Jenkinsfile to deploy to tokyo
- Monitoring
  - [x] configure NR synthetics and APM alert policies
  - [x] configure cloudwatch alerts
- [x] pre-prod acceptance checks
  - [x] mitigate previously unidentified issues
- [x] route prod traffic via route53 traffic policy (Created policy 13)
- [x] update status.mozmar.org with new app + synthetics

**Comment by jgmize** [comment]
@glogiotatidis 

- `snippets-prod` deis app created on tokyo cluster
  - but only partially configured
  - see TODOs in `deis config:list` output
- Redis elasticache and S3 bucket have been created by the tf in https://github.com/mozmar/ee-infra-private/pull/79 
  - however @metadave mentioned the possibility of needing to manually delete the bucket to get the latest TF to apply, so haven't filed bug to add s3 bucket to CF dist yet. 
- see updated list in issue description for other remaining tasks

**Comment by metadave** [comment]
Do we need the following command (w/ `s/virginia/tokyo/g`)

```
deis2 config:set ALLOWED_HOSTS=snippets-prod.virginia.moz.works,snippets-prod.moz.works,snippets.cdn.mozilla.net,snippets-prod-cdn.moz.works,snippets.mozilla.com -a snippets-prod
```
referenced from [here](https://github.com/mozmar/ee-infra-private/tree/master/certs/snippets)?

**Comment by jgmize** [comment]
Already taken care of:

```sh
$ DEIS_PROFILE=tokyo deis2 config:list -a snippets-prod | grep ALLOWED_HOSTS
ALLOWED_HOSTS                    snippets-prod.tokyo.moz.works,snippets-prod.moz.works,snippets.cdn.mozilla.net,snippets-prod-cdn.moz.works,snippets.mozilla.com
```

**Comment by jgmize** [comment]
Jenkins tokyo deployment added in https://github.com/mozmar/snippets-service/commit/5a285dea3c7b60214eb6b4d61131478cfc3214de

**Comment by metadave** [comment]
old news, but linking here for future reference -
Snippets infra Terraform: https://github.com/mozmar/infra/pull/127

**Comment by metadave** [comment]
Snippets and Careers ELB's provisioned via https://github.com/mozmar/infra/pull/170
