### ISSUE TITLE
Virginia snippets service: mitigate increased gunicorn worker timeouts

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#117]
- https://github.com/benoitc/gunicorn/issues/1194
- service currently using default TCP & SSL termination configured via k8s annotations
  - tested http & https listeners, found significant latency increase
  - significantly increased latency triggered route 53 traffic policy to shift prod traffic away automatically
  - also tested deis router with similar results
- next steps
  - [ ] deploy to tokyo #116 
    - this will allow us to eliminate (or identify) cross-AZ networking as a significant source of timeouts due to Tokyo being a single-AZ cluster
    - https://github.com/mozmar/infra/issues/117#issuecomment-294089564
  - [ ] test alternate gunicorn workers
    - [X] gevent: https://github.com/mozmar/infra/issues/117#issuecomment-294089564
    - [X] eventlet: https://github.com/mozmar/snippets-service/pull/231
    - [X] gthread: https://github.com/mozmar/snippets-service/pull/232
    - [X] meinheld: https://github.com/mozmar/snippets-service/pull/234 
  - [ ] test alternatives to gunicorn
    - [ ] uwsgi
    - [ ] ?

**Comment by metadave** [comment]
@jgmize mentioned that the K8s-created ELB uses a TCP health check, which could be causing issues with Gunicorn. We're looking into it.

**Comment by jgmize** [comment]
Going to try the new health checks in virginia first, then tokyo. updating route53 traffic policy to use new ELBs discussed in #159

**Comment by jgmize** [comment]
- health checks alone did not help in virginia
- started getting errors *after* getting traffic
  - sentry examples
    - https://sentry.prod.mozaws.net/marketing/snippets/issues/393983/
    - https://sentry.prod.mozaws.net/marketing/snippets/issues/393988/
    - https://sentry.prod.mozaws.net/marketing/snippets/issues/393989/
- tried gevent in virginia 
  - WIP PR: https://github.com/mozmar/snippets-service/pull/230
  - deployed in https://ci.us-west.moz.works/blue/organizations/jenkins/Snippets/detail/virginia/1/pipeline
  - timeout problem got worse; all requests failed; rolled back

**Comment by jgmize** [comment]
While testing the gthread worker in https://github.com/mozmar/snippets-service/pull/232 I found that I couldn't use it without upgrading gunicorn, then I went back to the sync worker and just upgraded gunicorn (see https://github.com/mozmar/snippets-service/pull/233) with no other changes. After letting it run in virginia for a bit with just the healthcheck traffic without seeing any timeouts, I decided to send a little prod traffic. After monitoring the logs I did see some gunicorn worker timeouts, but far fewer than we were seeing before, and no other issues were visible in NR.

**Comment by jgmize** [comment]
After letting snippets run with prod traffic for a while longer, the gunicorn worker timeout rate increased to about what we were seeing before, and I routed snippets prod traffic back away from virginia.

**Comment by jgmize** [comment]
I've deployed https://github.com/mozmar/snippets-service/pull/234 to virginia-prod and routed traffic to it. So far so good: no timeouts, no errors, no performance issues (possibly even a slight performance improvement, but it's within the margin of error so far).

**Comment by jgmize** [comment]
mozmar/snippets-service#234 has been deployed to virginia and tokyo, and both have been handling production traffic with no new timeouts, errors, or performance issues.
