### ISSUE TITLE
MDN MySQL to Postgres migration investigation

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#121]
Investigate different approaches to get data from MySQL w/ custom collation into Postgres.

See also:
https://github.com/mozilla/kuma/pull/3719
https://ngineered.co.uk/blog/using-amazon-efs-to-persist-and-share-between-conatiners-data-in-kubernetes
https://github.com/robhudson/mdn-pgloader

**Comment by metadave** [comment]
# MDN MySQL to Postgres experimentation


### Test 1: mdn-pgloader

Using the previous work from [mdn-pgloader](https://github.com/robhudson/mdn-pgloader), I was able to perform a *partial* migration. The pgloader process crashed with a `Killed` message, leaving 60978 out of 114459 total rows in the `wiki_document` table. Note that there may be more tables with errors, however I stopped here as >50% of data missing from a table seemed significant.

	2017-04-04T18:55:46.340000Z ERROR wiki_document: Illegal UTF-8 character starting at position 78: 237

> Searching for the error above in DuckDuckGo didn't bring up the following Github issue, which Google returned when I searched for it again a day later: 
> https://github.com/dimitri/pgloader/issues/124

Enabling verbose and debug tracing didn't uncover a row or specific data that caused the error. I messed around with various character set options in MySQL without success.

@jwhitlock was able to provide the following variables from the prod MySQL instance, but I'd like to additionally see the `/etc/mysql/my.cnf` file.

```
mysql> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

mysql> show variables like 'collation%';
+----------------------+-------------------+
| Variable_name        | Value             |
+----------------------+-------------------+
| collation_connection | latin1_swedish_ci |
| collation_database   | utf8_general_ci   |
| collation_server     | utf8_general_ci   |
+----------------------+-------------------+
3 rows in set (0.00 sec)
```

This route needs a bit more investigation, which I'll work on today. 

### Test 2: Migration data via AWS DMS and AWS Schema Conversion Tool

- https://aws.amazon.com/dms/
- https://aws.amazon.com/documentation/SchemaConversionTool/

I started an AWS instance in `us-east-2` and ran an MDN MySQL Docker container to import data similar to the initial instructions of mdn-pgloader. Once data was imported (about 45 mins), I ran the following 4 sql statements (also from mdn-pgloader) against the imported data:

```
ALTER TABLE taggit_tag MODIFY name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE wiki_documenttag MODIFY name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE wiki_localizationtag MODIFY name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE wiki_reviewtag MODIFY name VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
```

Once the source data was ready, I used the AWS [Schema Conversion Tool](https://aws.amazon.com/documentation/SchemaConversionTool/), which reported that 100% of our schema could be migrated. 

<img width="1001" alt="create_new_database_migration_project" src="https://cloud.githubusercontent.com/assets/58244/24761315/fee8a55c-1ab8-11e7-9483-e0c2c6d984f1.png">


Hey, that sounds great, right? Once I messed with security groups between source/target/DMS migration instance, I was able to create the target schema successfully.

However, running the DMS migration resulted in **22 out of 44 tables failing to migrate**. [Logs for DMS are terrible](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logEvent:group=dms-tasks-metadave-mdn-mysql-to-postgres;stream=dms-task-RQAQNFHP76F4K5KCFQN7QJXXTE). The errors seemed to be a combination of many issues, including foreign key constraint violations etc.

![database_migration_service](https://cloud.githubusercontent.com/assets/58244/24761340/0fd06364-1ab9-11e7-9ea0-290551d1e641.png)

---

## Current Recommendation

I'm going to experiment with pgloader a bit more, specifically using the settings from [this issue](https://github.com/dimitri/pgloader/issues/124). If migration via mdn-pgloader is still unsuccessful after a few more hours, I'm thinking that it might be best to either:

- a) Plan on using Python to manually migrate each table 
	- This is a larger task and could probably be completed best by someone who knows the schema and data.
- b) run our own MySQL w/ custom collation in prod until we have additional time to perform (a).


## TODO

- request a copy of production MySQL configuration.
- https://github.com/dimitri/pgloader/issues/124

**Comment by metadave** [comment]
ok, round 2 of pgloader testing resulted in a different # of rows being migrated, but still failed. I played around with the fix described in https://github.com/dimitri/pgloader/issues/124, however, we don't have any `binary` columns, and it wasn't apparent what exactly was erroring in the first place.

**Comment by jwhitlock** [comment]
Would it help if I find the records in the Document table with badly encoded fields?

**Comment by metadave** [comment]
@jwhitlock I think that might help, but I'm still unsure how for I'll get with pgloader.

**Comment by jwhitlock** [comment]
After a little investigation, I'm not sure how to find the records. I tried looking for badly encoded fields using the Django shell, but Django and the MySQL driver converts strings to the unicode type, hiding any issues, so I can't do it with Python.  I'd need to get pgloader into a debug mode to report what record is causing the issue, and then dig into that record for patterns.

I'm OK with saying "investigation closed" and putting this effort on the back-burner until we have more time to tackle it (SF in June?) and proceed with hosted MySQL for now.  We can defer the backups questions until we're closer to migrating to AWS. Until then, our plans are to work with production backups and sample databases, so data loss won't have a huge impact.

**Comment by metadave** [comment]
Thanks @jwhitlock. After my initial investigation, I'm thinking the best/safest/most accurate route would be a programmatic migration.
