### ISSUE TITLE
install Cloudflare->Datadog via helm chart

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#122]
when complete, decom existing integration https://github.com/mozmar/infra/issues/123

**Comment by metadave** [comment]
Submitted a few upstream fixes to this PR: https://github.com/kubernetes/charts/pull/780#issuecomment-306223021

**Comment by metadave** [comment]
installed. @glogiotatidis do you have a couple minutes on Tuesday to see if this is running correctly?

**Comment by glogiotatidis** [comment]
Works fine! 👍 

- I created a new Datadog dashboard for the new prefix 
- Stopped (but not deleted) the deisv1 `cloudflare-datadog-sync` app from us.west
