### ISSUE TITLE
Tokyo reports to Virginia's destrination in Papertrail 

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#125]

**Comment by metadave** [comment]
ah, this is due to `ee-infra-private/k8s/clusters/tokyo/config.sh` using virginia's `SYSLOG_HOST`, `SYSLOG_PORT`. We'll have to reinstall the [fluentd chart](https://github.com/mozmar/infra/blob/master/k8s/install/stage2_functions.sh#L101-L104) with the correct values.

**Comment by metadave** [comment]
Fixed via https://github.com/mozmar/ee-infra-private/pull/80, removed previous chart installation and reinstalled with new values.

**Comment by glogiotatidis** [comment]
🤘
