### ISSUE TITLE
Deploy Careers to Tokyo

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#140]
- [x] Create App
- [x] Jenkins Perms
- [x] Setup environment vars
- [x] Update Jenkinsfile
- [x] Test deployment
- [x] Setup Sentry
- [x] Setup careers.mozilla.org domain
- [x] Setup Synthetics monitors
- [x] Update status.mozmar.org
~~- [ ] Create Route53 Health Checks (via TF?)~~
~~- [ ] Create Traffic Policy~~
~~- [ ] SSL Cert and ELB + k8s service for careers.mozilla.org (see also https://github.com/mozmar/ee-infra-private/pull/81)~~
~~- [ ] Resolve SSL Redirection issue (See also #101)~~
- ~~[ ] Setup limits and hpa~~ (See #165)

**Comment by glogiotatidis** [comment]
Unchecking the ELB entry until we figure out mozmar/ee-infra-private#82

**Comment by glogiotatidis** [comment]
Removed all ELB related  tasks due to #159

**Comment by glogiotatidis** [comment]
Deploying careers tokyo to production is blocked by http->https redirector which is handled in another bug.

**Comment by metadave** [comment]
Redirection PR: https://github.com/mozmar/infra/pull/163

**Comment by jgmize** [comment]
Resolved performance issues and timeouts via mozmar/lumbergh#194 and the tokyo careers deployment is now in prod.
