### ISSUE TITLE
Deploy Careers to Virginia

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#141]
- [x] Create App
- [x] Jenkins Perms
- [x] Setup environment vars
- [x] Update Jenkinsfile
- [x] Test deployment
- [x] Setup Sentry
- [x] Setup careers.mozilla.org domain
- [x] Setup Synthetics monitors
- [x] Update status.mozmar.org
~~- [ ] Create Route53 Health Checks (via TF?)~~
~~- [ ] Create Traffic Policy~~
~~- [ ] SSL Cert and ELB + k8s service for careers.mozilla.org (see also https://github.com/mozmar/ee-infra-private/pull/81)~~
~~- [ ] Resolve SSL Redirection issue (See also #101)~~
~~- [ ] Setup limits and hpa~~ (See #165)

**Comment by glogiotatidis** [comment]
Unchecking the ELB entry until we figure out https://github.com/mozmar/ee-infra-private/pull/82

**Comment by glogiotatidis** [comment]
Removed all ELB related entries due to #159

**Comment by glogiotatidis** [comment]
Deploying careers virginia to production is blocked by http->https redirector which is handled in another bug.

**Comment by metadave** [comment]
Redirection PR: https://github.com/mozmar/infra/pull/163

**Comment by metadave** [comment]
@glogiotatidis the (new) `careers` ELB in `us-east-1` has a health check that requests `/` from the `careers` nodeport, but takes 25-45 seconds to return. Instances show OutOfService as a result of this. Tested via `curl`.

**Comment by jgmize** [comment]
Resolved performance issues and timeouts via https://github.com/mozmar/lumbergh/pull/194 and the tokyo careers deployment is now in prod.
