### ISSUE TITLE
MDN AWS architecture eval and recommendation

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#147]
# MDN AWS architecture evaluation and recommendation

MDN Migration plan [here](https://docs.google.com/document/d/1-s343yxBMiugPQm5w2ho7EcSAcaLU4uOF6p2MLgbS1I/edit#)

## Serving HTTP

Apache HTTPD currently services traffic out of SCL3 with a highly customized configuration. Some of our migration options are as follows:

1. Run HTTPD "as-is" on standalone EC2 instances, with modifications to point to new backend AWS services.
	2. Could be a quick hit, but with a significant amount of technical debt carried forward.
	3. Difficult maintenance
	4. We'd have to come up with an autoscaling solution to add new instances to the cluster if needed.
2. Run HTTPD in Kubernetes
	3. 	This solution is similar to the one above, however, we'd get autoscaling "for free" if we specify the container requests/limits 
	4. I couldn't get httpd running in Kubernetes during the Toronto work week, however, it's worth taking another look.
3. Convert HTTPD config to Python
	4. This carries the least amount of technical debt forward and greatly simplifies deployment in AWS and Kubernetes, however, it can also be fairly involved to understand and convert the httpd config.

## File storage

We can use either S3 buckets and/or EFS.

More info [here](https://docs.google.com/document/d/1_JtwNQv2zyrVkZ3mLuu3-zEVbrwaVH8ErdDTe4GUy9U/edit#heading=h.88l66nuhk518)

## Database

- MySQL with custom collation hosted in Kubernetes
	- move database as-is to hosted Kubernetes.
	- We'll have to manage backup/restore/upgrades
- MySQL with custom collation hosted on standalone EC2 instance(s)
	- if persistent volumes present problems
- MySQL migrated to Postgres, running in RDS
	- this is the preferred method, but there are technical hurdles to overcome.
	- RDS gives us backups and automatic minor version updates "for free"
	- initial investigation documented [here](https://github.com/mozmar/infra/issues/121)

---

### TODO

- [x] create subtask investigation cards
- [x] request current apache config/puppet info from webops

**Comment by metadave** [comment]
MySQL->PGSql migration notes [here](https://github.com/mozmar/infra/issues/121)

**Comment by metadave** [comment]
request for current Apache SCL3 config [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1357511)

**Comment by jgmize** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1357511#c1 for links to apache config and SCL3 docs.

**Comment by metadave** [comment]
- Storage analysis [here](https://github.com/mozmar/infra/issues/183#issuecomment-296221977)
- Apache analysis [here](https://github.com/mozmar/infra/issues/180#issuecomment-296233021)

**Comment by jgmize** [comment]
Elasticsearch evaluation #193

**Comment by metadave** [comment]
Summary:

- [File storage](https://github.com/mozmar/infra/issues/183)
	- store all additional media ([including samples](https://github.com/mozmar/infra/issues/197)) on EFS.
- [Serving HTTP](https://github.com/mozmar/infra/issues/180)
	- Django hosts everything, completely removing httpd.
- [Database](https://github.com/mozmar/infra/issues/121)
	- We're sticking with self-hosted MySQL running per-region in Kubernetes.
	- We'll need [a custom backup solution](https://github.com/mozmar/infra/issues/198)
- [Elasticsearch](https://github.com/mozmar/infra/issues/193)
	- (waiting for [confirmation](https://github.com/mozmar/infra/issues/193#issuecomment-301583226)) for the initial migration, use AWS hosted ES, keeping in mind that we can always self-host.
