### ISSUE TITLE
Create Traffic Policy for Snippet Stats

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#150]
- [x] Health checks
- [x] Traffic Policy
- [x] Add domain snippets-stats.moz.works to Deis apps
- [x] Configure snippets-prod everywhere to use snippets-stats.moz.works
- [x] ELBs and SSL certs
- [x] Document and pull request changes

**Comment by glogiotatidis** [comment]
For this we'll need a Cert. @metadave do we have a howto get / manage certs for  services?

**Comment by glogiotatidis** [comment]
Also we need to create the ELB via TF according to #159 ?

**Comment by metadave** [comment]
@glogiotatidis regarding managed certs, we don't have a howto _yet_, but I created an [issue](https://github.com/mozmar/infra/issues/167) to make one.

Also, I believe we'll need an ELB unless we decide to take a different route.

**Comment by glogiotatidis** [comment]
> Also, I believe we'll need an ELB unless we decide to take a different route.

Agreed. The (poorly asked) question was about using terraform or doing it using k8s

**Comment by metadave** [comment]
I'd suggest creating a `LoadBalancer` in K8s to see your app work, then we can create/apply a Terraform managed ELB after (or once we have everything straightened out).

**Comment by glogiotatidis** [comment]
Agreed! I'll need a cert when you have the time. Thanks!

**Comment by metadave** [comment]
just to verify, you need a cert for `snippets-stats.mozilla.org`?

**Comment by metadave** [comment]
howto for ACM certs: https://github.com/mozmar/infra/pull/169

**Comment by glogiotatidis** [comment]
For snippets-stats.moz.works but not that there's a howto I'll review by following it. Thanks @metadave

**Comment by jgmize** [comment]
We now have the following region-specific certs available for snippets-stats.moz.works:
- arn:aws:acm:us-east-1:236517346949:certificate/caf5907d-9804-4a16-9f3f-29193fb25565
- arn:aws:acm:ap-northeast-1:236517346949:certificate/3fd8337d-9476-46a9-acda-47abc3b95472
- arn:aws:acm:us-west-2:236517346949:certificate/9c1fa86d-d2da-4d54-b07d-33c200c3a967
- arn:aws:acm:eu-west-1:236517346949:certificate/bc268ec4-0afd-4d83-be8b-36209b363eff

**Comment by metadave** [comment]
`us-west-2` and `eu-west-1` ELB's were created manually, and attached to ELB's with the following:

```
aws autoscaling attach-load-balancers \
    --auto-scaling-group-name "deis-1-13-2-CoreOSServerAutoScale-K94Z0XD5SECC" \
    --load-balancer-names snippets-stats \
    --region "us-west-2"

aws autoscaling attach-load-balancers \
    --auto-scaling-group-name "deis-1-13-2-CoreOSServerAutoScale-1A69CS3X5KWYO" \
    --load-balancer-names snippets-stats \
    --region "eu-west-1"
```

**Comment by jgmize** [comment]
ELBs and traffic policy created, all 4 snippets-services deployments configured to use `ALTERNATE_METRICS_URL=https://snippets-stats.moz.works/foo`
