### ISSUE TITLE
Upgrade Jenkins Core and Plugins

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#152]
- [X] cleanup docker images
   - [X] backup jenkins
   - [X] upgrade jenkins debian package
   - [x] upgrade jenkins plugins
   - [X] restart registries

**Comment by glogiotatidis** [comment]
Includes core upgrades, security updates for plugins and BlueOcean v1.0 \o/

**Comment by glogiotatidis** [comment]
There's still a notification in jenkins of a security advisory which doesn't have a package update yet. The advisory is about overriding the Pipelines sandbox which is not affecting us since we consider code we run trusted.

**Comment by metadave** [comment]
excellent!

do you have any notes on cleaning up docker images, backup, and restarting registries?

**Comment by glogiotatidis** [comment]
Thanks for asking @metadave ;)

https://github.com/mozmar/infra/pull/155
