### ISSUE TITLE
Install new cert for basket.mozilla.org

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#154]
- https://bugzilla.mozilla.org/show_bug.cgi?id=1350929
  - received encrypted copy of new cert & key from @joekrejci
- current cert expires on April 11, 2017
- [x] upload cert to aws
- [x] install in us-west ELB
- [x] install in eu-west ELB

**Comment by joekrejci** [comment]
Just wanted to check in on this, it expires in less than 13 hours now. @jgmize

**Comment by metadave** [comment]
@joekrejci jgmize is on PTO today. I can take care of it right now if you like, but I don't have access to the bugzilla issue.

cc @bensternthal

**Comment by pmac** [comment]
@metadave I added you to the bug

**Comment by metadave** [comment]
New certs have been installed in us-west-2 and eu-west-1

**Comment by metadave** [comment]
I'll submit a PR to ee-infra in a bit

**Comment by jgmize** [comment]
Thanks again @metadave!
