### ISSUE TITLE
[snippets-stats] Configure app limits and autoscaling

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#164]
Configure app limits and autoscaling for

 - [ ] Snippets-stats Tokyo
 - [ ] Snippets-stats Virginia

**Comment by metadave** [comment]
based on the [Deis resource limits docs](https://deis.com/docs/workflow/applications/managing-resource-limits/), I'm thinking of using:

```bash 
deis limits:set cmd=512M/1024M
deis limits:set cmd=500m/750m --cpu
```

However, I'm unsure about this services typical workload.

**Comment by glogiotatidis** [comment]
On Tokyo I set the following and it works fine

```
deis_tokyo autoscale -a snippets-stats
=== snippets-stats Autoscale

--- cmd:
Min Replicas: 3
Max Replicas: 10
CPU: 80%
```

```
deis_tokyo limits -a snippets-stats
=== snippets-stats Limits

--- Memory
cmd     128M

--- CPU
cmd     50m
````

**Comment by glogiotatidis** [comment]
Set the same limits to virginia.
