### ISSUE TITLE
[careers] Setup app limit and autoscaling

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#165]
Setup app limit and autoscaling for 

 - [ ] Careers Virginia
 - [ ] Careers Tokyo

**Comment by metadave** [comment]
@glogiotatidis @jgmize any objections to using these limits?

```
deis limits:set cmd=600M/1024M
deis limits:set cmd=250m/500m --cpu
deis autoscale:set cmd --min=3 --max=5 --cpu-percent=80
```

**Comment by glogiotatidis** [comment]
The limits are per instance right? I believe that 600M is pretty high, as careers-prod.web instances weight about 120Mb each atm.

**Comment by metadave** [comment]
right, I was going off the UI, which I'm now guessing is memory across the cluster:
![kubernetes_dashboard](https://cloud.githubusercontent.com/assets/58244/25956844/d6a782f0-363a-11e7-9007-ed8e931fbf7b.png)

vs

```
ε 🔥 ~ $ kubectl -n careers-prod top pods
NAME                                CPU(cores)   MEMORY(bytes)
careers-prod-web-4246055684-7v4qs   0m           107Mi
careers-prod-web-4246055684-w7t3l   0m           109Mi
careers-prod-web-4246055684-v88qr   0m           104Mi
careers-prod-web-4246055684-wcjq3   0m           106Mi
careers-prod-web-4246055684-m5k7c   0m           108Mi
```

limits updated above

**Comment by jgmize** [comment]
Updated limits lgtm

**Comment by metadave** [comment]
oops, I think this should specify `web` instead of `cmd`:

```
deis limits:set web=120M/300M
deis limits:set web=250m/500m --cpu
deis autoscale:set web --min=3 --max=5 --cpu-percent=80
```

**Comment by metadave** [comment]
all set in tokyo and virginia.

**Comment by glogiotatidis** [comment]
Thanks Dave!
