### ISSUE TITLE
validate metrics for snippets-stats in Virginia and Tokyo

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#174]
As described in https://github.com/mozmar/infra/issues/150#issuecomment-294585199 all snippets deployments now use the same URL  rather than region specific URLs as used previously. The initial traffic policy is only routing traffic to the snippets-stats services in Dublin and Portland, as we have not yet validated the snippets-stats services in Tokyo or Virginia yet-- indeed, the Virginia stats were suspiciously low when we ran some production traffic to it on Friday and part of Saturday. Once we've had enough time for the clients to update to the new traffic policy backed URL we can enable each of the new deployments in turn, validating that the resulting metrics are in the expected range and troubleshooting if necessary.

**Comment by jgmize** [comment]
- [ ] identify cache timeout for previously generated snippets with old URLs, if it exists
- [ ] clear previously generated snippets from s3 in tokyo and virginia, if necessary

**Comment by jgmize** [comment]
- [ ] link to new or existing snippets stats low metrics alarm documentation
  - [ ] identify specific alarm thresholds
- [ ] compare timing of alarms with [datadog dashboard](https://app.datadoghq.com/dash/275589/jmizes-timeboard-14-apr-2017-1951?live=true&page=0&is_auto=false&from_ts=1491864187515&to_ts=1492468987515&tile_size=m) and NR [throughput](https://rpm.newrelic.com/accounts/1299394/applications/23656273) [in](https://rpm.newrelic.com/accounts/1299394/applications/24982923) [each](https://rpm.newrelic.com/accounts/1299394/applications/13687704) [region](https://rpm.newrelic.com/accounts/1299394/applications/13687987).

**Comment by glogiotatidis** [comment]
> clear previously generated snippets from s3 in tokyo and virginia, if necessary

You can force the service to regenerate by clearing the cache with `./manage.py clear_cache`

**Comment by metadave** [comment]
cleared in tokyo and virginia

**Comment by metadave** [comment]
Updated snippets-prod to use traffic policy version 17 (Oregon, Virginia, Ireland)

**Comment by jgmize** [comment]
@glogiotatidis while we have been routing snippets-service traffic to all 4 regions listed above, the snippets-stats traffic policy has only enabled Portland and Dublin, but we've still been seeing intermittent alerts from https://app.datadoghq.com/monitors#1867699 so I'm thinking that we need to lower the alert thresholds and enable Tokyo ~Drift~ traffic. What do you think?

**Comment by glogiotatidis** [comment]
I see that you lowered the threshold to 10k per hour 👍 

Numbers look OK, i'm adding tokyo

**Comment by glogiotatidis** [comment]
```
deis_tokyo autoscale -a snippets-stats
=== snippets-stats Autoscale

--- cmd:
Min Replicas: 3
Max Replicas: 10
CPU: 80%
```

**Comment by glogiotatidis** [comment]
```
deis_tokyo limits -a snippets-stats
=== snippets-stats Limits

--- Memory
cmd     128M

--- CPU
cmd     50m```

**Comment by glogiotatidis** [comment]
Things look OK atm, i'll continue to watch the metrics today

**Comment by glogiotatidis** [comment]
Everything seems to be working. Any objections to add virginia to the pool?

**Comment by metadave** [comment]
@glogiotatidis sounds good to me, thanks for doing this!

**Comment by glogiotatidis** [comment]
Set limits and added virginia in the pool

**Comment by glogiotatidis** [comment]
things look fine in virginia kai overall
