### ISSUE TITLE
move Basket to Kubernetes

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#179]
- [x] Virginia basket IAM cert
- [x] Tokyo basket IAM cert
- [x] Virginia nodeport
- [x] Tokyo nodeport
- [x] Virginia ELB provisioning
- [x] Tokyo ELB provisioning

**Comment by metadave** [comment]
- [ ] Virginia basket IAM cert
- [ ] Tokyo basket IAM cert
- [ ] Virginia nodeport
- [ ] Tokyo nodeport
- [ ] Virginia ELB provisioning
- [ ] Tokyo ELB provisioning

**Comment by metadave** [comment]
ELB provisioning wip here: https://github.com/mozmar/infra/compare/dp_basket_elbs?expand=1

**Comment by jgmize** [comment]
We do not currently have SES provisioning automated, and basket is using SES endpoints that were provisioned manually in other regions. Will follow up in future issue automating SES and/or other email service deployment.

**Comment by metadave** [comment]
```
deis2 limits:set web=300M/600M -a basket-stage
deis2 limits:set web=250m/1000m --cpu -a basket-stage
deis2 autoscale:set web --min=5 --max=20 --cpu-percent=80 -a basket-stage

deis2 limits:set web=300M/600M -a basket-prod
deis2 limits:set web=250m/1000m --cpu -a basket-prod
deis2 autoscale:set web --min=5 --max=20 --cpu-percent=80 -a basket-prod
```

**Comment by metadave** [comment]
Traffic policies are all set (but not enabled) in Virginia and Tokyo for both stage and prod.

**Comment by metadave** [comment]
make it so.

**Comment by metadave** [comment]
![628b747f8ccdfb757062f36a27eedecfc2295f515c0586e05fbfb0620c0571a2](https://user-images.githubusercontent.com/58244/26901708-beae302a-4ba4-11e7-95fe-a17ffafb7dc6.jpg)
