### ISSUE TITLE
Investigate running HTTPD on Terraform/Ansible provisioned nodes

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#182]
[Parent issue](https://github.com/mozmar/infra/issues/147)

Once we have the [SCL3 Apache config](https://bugzilla.mozilla.org/show_bug.cgi?id=1357511), determine:

- the amount of effort required to run HTTPD on Terrform and Ansible provisioned nodes (non-Kubernetes).

AWS instances can be provisioned with Terraform, and TF outputs can be passed to Ansible to perform the remaining node config.

**Comment by jgmize** [comment]
While this is technically possible, I would very much like to avoid this approach. Fortunately it looks like you're already making good progress in https://github.com/mozmar/infra/issues/181#issuecomment-295516006 so it's unlikely that we will need to do this.

**Comment by metadave** [comment]
Also, (in theory) webops should be able to point their Puppet stuff at new EC2 nodes and provision them for us, minus some misc IP changes in the config.

**Comment by jgmize** [comment]
> Also, (in theory) webops should be able to point their Puppet stuff at new EC2 nodes and provision them for us, minus some misc IP changes in the config

Sorry, I don't think that will be possible in practice due to some limitations that we can discuss in a different medium.

**Comment by metadave** [comment]
More info [here](https://github.com/mozmar/infra/issues/180)
