### ISSUE TITLE
move nucleus to Kubernetes

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#184]
- [x] deis workflow apps or ~k8s yaml template~ rendered and installed
  - [x] virginia
  - [ ] ~tokyo~
- [ ] DB
  - [x] use existing Bedrock RDS instance in Virginia
    - ~master instance in Virginia, replica in Tokyo~
  - [x] backup from Portland, restore to Virginia
    - ~verify automatic data replication to Tokyo~

- [x] ELBs via Terraform
  - [X] SSL certs via ACM
    - [X] virginia 
      - arn:aws:acm:us-east-1:236517346949:certificate/fa2f75df-e710-4e2a-b210-2647c4179dac
    - [X] tokyo
      - arn:aws:acm:ap-northeast-1:236517346949:certificate/38fd2f56-1705-4aff-ad57-5b369d29a804
- [x] DNS change
  - nucleus.mozilla.org is a CNAME to nucleus.moz.works
  - [x] schedule brief window with no edits
  - [x] backup from Portland, restore to Virginia
  - [x] point nucleus.moz.works to virginia ELB alias

**Comment by metadave** [comment]
https://github.com/mozmar/infra/pull/266

**Comment by metadave** [comment]
@jgmize are we going to do the automatic data replication to Tokyo?

**Comment by jgmize** [comment]
The release notes data are replicated to all of the bedrock instances at the application level, and the user, group, and permissions data change rarely, so backups should be sufficient. I don't believe a Tokyo deployment of nucleus should be necessary.
