### ISSUE TITLE
Investigate MDN EFS replication strategy

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#189]
[Parent issue](https://github.com/mozmar/infra/issues/147)

We need a method to easily and safely replicate data between EFS volumes.
More info [here](https://github.com/mozmar/infra/issues/183#issuecomment-296221977)

**Comment by metadave** [comment]
Initial thoughts: (click to expand)

![efs_multi-region_sync_xmind](https://cloud.githubusercontent.com/assets/58244/25455923/6442c2c0-2a9f-11e7-8f58-3a8f9ca3595c.png)

**Comment by jgmize** [comment]
I don't think we need to handle multi-master replication for the initial implementation. A single region will host the master, all other regions will be in read-only maintenance mode. We will have automated failover of production traffic via route53 traffic policy, but promoting a new region to master to restore editing capabilities & file uploads can be a manual process that we should document and run through before going to full production.

**Comment by jgmize** [comment]
For anything that needs multi-master file access, I think git, with [lfs](https://git-lfs.github.com/) if necessary, probably makes the most sense.

**Comment by metadave** [comment]
closing this and will followup with an implementation card some time in the future.

**Comment by metadave** [comment]
instead of using rsync over ssh, which could get tricky due to dynamic public node IP's and firewalls between VPC's, we could simply sync master **to** S3, and then have other regions pull **from** S3:

Master to backup:

```
aws s3 sync ./ s3://mdn-shared-backup
```

sync non-master region(s) from backup:
```
aws s3 sync s3://mdn-shared-backup ./ 
```

The only con I can think of is that each sync will happen on a node in a given region, instead of on a single node serially controlling reads/writes across all regions. It may be possible to get partial sync results, but this will become more consistent with each subsequent sync.

This kills 2 birds with one stone: backup and sync in just a few lines of code + a few sets of limited IAM creds. 

is this a terrible idea @jgmize?

**Comment by jgmize** [comment]
Great idea @metadave! Let's do that.
