### ISSUE TITLE
Automatic recovery of basket FxA Activity worker

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#196]
Once https://github.com/mozmar/infra/issues/179 is complete, we can add a [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) for the fxaworker task that will cause kubernetes to automatically restart the worker when necessary.

**Comment by jgmize** [comment]
the worker runs https://github.com/mozmar/basket/blob/master/news/management/commands/process_fxa_data.py via https://github.com/mozmar/basket/blob/master/bin/run-fxa-activity-worker.sh as configured in https://github.com/mozmar/basket/blob/master/Procfile#L4

**Comment by jgmize** [comment]
@pmac may have ideas on how to make the fxaworker more robust in the near term even before the k8s migration

**Comment by jgmize** [comment]
instead of relying on the python scheduler in a long-running container, we could launch short-lived containers running the management command (without the `--cron` arg) via an external scheduler-- actual cron on an admin node, [k8s cron](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/), jenkins scheduled tasks, etc.

**Comment by jgmize** [comment]
@metadave would rather avoid enabling alpha APIs on on our k8s clusters, which would mean holding off on k8s cron for at least another release cycle. Setting up a jenkins job to trigger the management command via `deis run` is probably the easiest solution that comes to mind, but it's not ideal, and I'm open to other options.

**Comment by pmac** [comment]
Main reason at the moment to do it via a single process is that it's taking WAY longer to run than we'd like, so it's skipping schedules as designed. What makes us believe it's not robust? The Snitch alerts are I'm pretty sure because it's taking longer than a day to run. My estimates for the initial run of 10 Million records was around 10 days. I changed the snitch to be weekly. Apologies for failing to stop the snitch or change it before I left.

**Comment by jgmize** [comment]
Ah, thanks for the clarification @pmac. I was under the impression that the daily snitch alerts were detecting the process was hung up and was manually restarting them. Sounds like there's no further action needed here.
