### ISSUE TITLE
WARNING - webwewant.mozilla.org SSL Cert Expires 5-03-17

### ISSUE THREAD

**Issue by joekrejci** [mozmar/infra#202]
Fri 13:01:08 UTC [unset] webwewant.mozilla.org:HTTPS - SSL Cert expiration is DOWNTIMEEND (WARNING): WARNING - Certificate 'webwewant.mozilla.org' expires in 4 day(s) (2017-05-03 12:00 +0000/UTC). (http://m.mozilla.org/HTTPS+-+SSL+Cert+expiration) (notify-by-email) WARNING - Certificate 'webwewant.mozilla.org' expires in 4 day(s) (2017-05-03 12:00 +0000/UTC). @jgmize

**Comment by metadave** [comment]
thanks for reporting @joekrejci!

**Comment by metadave** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1354665

**Comment by metadave** [comment]
https://github.com/MozillaFoundation/plan/issues/375#issuecomment-274885479

**Comment by jgmize** [comment]
Closing in favor of #203
