### ISSUE TITLE
Decom webwewant.mozilla.org

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#203]
- https://bugzilla.mozilla.org/show_bug.cgi?id=1354665#c4
- https://github.com/MozillaFoundation/plan/issues/375#issuecomment-274885479

**Comment by jgmize** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1361114 asking webops to point DNS to SCL3 and redirect to www.mozilla.org. Once this is complete we will delete the Deis apps and ELBs.

**Comment by danielhartnell** [comment]
Hey @jgmize,

Bugzilla bug: 1361114 has been resolved. The redirect is in place and it should be functioning well. If you notice any unexpected behavior, please let me know.

Cheers!

**Comment by jgmize** [comment]
Thanks @danielhartnell. I've deleted the ELB, webwewant.moz.works A & AAAA records, and deis app.
