### ISSUE TITLE
Decom http://openwebdevice.org/

### ISSUE THREAD

**Issue by bensternthal** [mozmar/infra#205]
Emailed 5/2
Julie McCracken <jmccracken@mozilla.com>
Karen Ward <kward@mozilla.com>

**Comment by bensternthal** [comment]
Waiting on Karen Ward approving the decom.

**Comment by bensternthal** [comment]
Heard back from stakeholders. This is a legal entity and a bit.. complicated. 

"I don’t see that we can fully decommission the site until we’ve gone through the proper interactions with the board in accordance with our bylaws."

So it sounds like we will gradually make updates to the site and slowly inch towards a decom.

I will close this for now since we do not have a timeline.

**Comment by metadave** [comment]
thanks @bensternthal 
just a heads up, the cert has already expired.

**Comment by jgmize** [comment]
IIRC we decided that http-only was sufficient for a static site with no login, saving the cost of a dedicated ELB for each region the site is deployed to. @bensternthal will you please confirm or correct my recollection?

**Comment by bensternthal** [comment]
Confirmed, http only on this site is OK.
