### ISSUE TITLE
basket SQS provisioning

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#208]
Create an SQS queue and IAM user/policy that we can securely share with FxA team.

https://bugzilla.mozilla.org/show_bug.cgi?id=1358123#c5

**Comment by metadave** [comment]
@pmac how do you want to handle dev/prod/stage? Separate queues?

**Comment by pmac** [comment]
@metadave my reading of the bug is that they'd like separate prod, stage, and dev queues. They will be the one writing to the queue, so whatever allows them that will be sufficient. Basket will be reading and removing messages from the queue(s).

**Comment by metadave** [comment]
ok, I see that SQS [allows 1mil messages/month free](https://aws.amazon.com/sqs/pricing/), so a dev and staging queue should be fine.

**Comment by metadave** [comment]
@pmac I'm going to use the SQS defaults, there are a bunch of [config options](https://www.terraform.io/docs/providers/aws/r/sqs_queue.html) that I can set as well. (ex: `max_message_size`, `fifo_queue`, etc). Let me know if you want anything tweaked or if I should copy an existing SQS config. What AWS regions do you SQS provisioned in?

**Comment by pmac** [comment]
I believe we want it in us-west-2, but I could be wrong. @rfk do you have any input on the location and configuration of these SQS queues?

**Comment by jbuck** [comment]
Yeah, us-west-2 please.

Do you want the our account numbers so you can setup cross-account access?

**Comment by metadave** [comment]
@jbuck I have to look into how we'll do security, but I'll most likely need your account #. Thanks!

**Comment by metadave** [comment]
I have 3 IAM users (one for each dev/stage/prod) setup, so I won't need the account numbers.

**Comment by metadave** [comment]
@pmac here's some sample Python code taken from the boto docs to test the SQS queues: https://gist.github.com/metadave/7191e7f173139719f695e896c037f669
