### ISSUE TITLE
Upgrade Deis Workflow to latest

### ISSUE THREAD

**Issue by pmac** [mozmar/infra#213]
As of filing the latest version is 2.14.0. We're currently on 2.10.0 in virginia. The new version brings with it a change that I'd really like: moves the app name max length from 24 to 63. We're used to 63 as that matches the deis v1 limit. I'm sure there are other improvements, but this is the one I'm interested in :)

**Comment by metadave** [comment]
related docs here: https://deis.com/docs/workflow/managing-workflow/upgrading-workflow/

**Comment by pmac** [comment]
Any ideas on ETA for this? No rush; I'm just trying to decide whether I should deal with the shorter limit in my bedrock PR for Deis Workflow deployment or not.

**Comment by metadave** [comment]
I'm not sure at the moment, probably worth discussing at the SRE weekly.

**Comment by metadave** [comment]
Also, I believe we need to pass in the config values that are generated by our stage 2 K8s installer: https://github.com/mozmar/ee-infra-private/blob/master/k8s/clusters/virginia/out/terraform/workflow_config_moz.yaml

**Comment by metadave** [comment]
We've create an upgrade script in [this PR](https://github.com/mozmar/infra/pull/219/).

**Comment by jgmize** [comment]
Upgraded Deis workflow to 2.14 in Tokyo and Virginia clusters.
