### ISSUE TITLE
plan for migrating mdn.mozillademos.org

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#214]
We'll have to ensure that redirects to mdn.mozillademos.org work when we go live. I'm unsure if mozillademos is the same thing as legacy sample hosting, as described in [this doc](https://github.com/mozmar/infra/issues/197).

From [this](https://docs.google.com/document/d/1-s343yxBMiugPQm5w2ho7EcSAcaLU4uOF6p2MLgbS1I/edit#heading=h.ud2bwt6gqa3k):

```
Live Samples and file serving
https://mdn.mozillademos.org is configured to serve files that could be dangerous to serve from developer.mozilla.org.  The Apache configuration is much simpler than for developer.mozilla.org and the CDN origin. 

Here is a URL to a live sample:

https://mdn.mozillademos.org/en-US/docs/MDN/Contribute/Structures/Live_samples$samples/Live_sample_demo

The Kuma application will generate an HTML document for the sample based on the page contents.

Here is a URL to an attachment:

https://mdn.mozillademos.org/files/14573/new%20Boolean(value)%202.png

The Kuma application will process the reference by ID and serve the file as a streaming response.
```

**Comment by jgmize** [comment]
Currently mdn.mozillademos.org is backed by the same kuma instances that power developer.mozilla.org, but kuma behaves differently based on the host header.
- the html for code samples only renders if the host matches `config.KUMA_WIKI_IFRAME_ALLOWED_HOSTS`: https://github.com/mozilla/kuma/blob/master/kuma/wiki/views/code.py#L27
  - `$samples` url regex: https://github.com/mozilla/kuma/blob/master/kuma/wiki/urls.py#L61
- the file attachments get served at urls matching [this regex](https://github.com/mozilla/kuma/blob/master/kuma/attachments/urls.py#L7) only if the host matches settings.ATTACHMENT_HOST: https://github.com/mozilla/kuma/blob/master/kuma/attachments/views.py#L40
  - note that these are served by kuma, not directly by apache

**Comment by metadave** [comment]
apologies for the delay, the buffer that I had notes in got killed.

- mdn.mozillademos.org must be migrated in Route 53 during the launch.]
- this must work in maintenance mode
- can we deploy this before the main migration?

**Comment by metadave** [comment]
We control the dns for `mdn-demos.moz.works`, which mdn.mozillademos.org is a CNAME for:

```
$ dig mdn.mozillademos.org

; <<>> DiG 9.8.3-P1 <<>> mdn.mozillademos.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25818
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mdn.mozillademos.org.		IN	A

;; ANSWER SECTION:
mdn.mozillademos.org.	3600	IN	CNAME	mdn-demos.moz.works.
mdn-demos.moz.works.	60	IN	A	63.245.215.74
```
