### ISSUE TITLE
K8s autoscaling

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#22]
- https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler
- https://github.com/coreos/kube-aws/issues/148
- https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cloudprovider/aws/README.md

**Comment by jgmize** [comment]
https://github.com/kubernetes/charts/tree/master/stable/aws-cluster-autoscaler

**Comment by metadave** [comment]
implemented here: https://github.com/mozmar/infra/pull/111
