### ISSUE TITLE
Investigate why dd-agent does not report CPU / mem usage on masters

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#227]

**Comment by jgmize** [comment]
Based on https://github.com/kubernetes/kops/issues/970#issuecomment-300174163 we may be able to fix this with `dnsPolicy: ClusterFirstWithHostNet` on new 1.6 clusters.

**Comment by metadave** [comment]
See [this PR's](https://github.com/mozmar/ee-infra-private/pull/95) content for more info on tolerances we've configured to enable DaemonSet pods to run on master nodes.
