### ISSUE TITLE
Analysis of accepted locates in Apache vs Django

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#242]
Comparing the SCL3 httpd config with [Kuma's](https://github.com/mozilla/kuma/blob/master/kuma/settings/common.py#L129), the only differences appear to be:

- `AddLanguage cs .cz .cs` (Czech)
- `AddLanguage da .dk` (Danish / Denmark)
- `AddLanguage eo .eo`  (Esperanto)
- `AddLanguage et .et` (Estonian)
- `AddLanguage ltz .ltz` (Luxembourgeois)
- `AddLanguage nn .nn` (Norwegian Nynorsk)

@jwhitlock should I submit a PR against Kuma adding any of these, or are they tech debt at this point?

[parent issue](https://github.com/mozmar/infra/issues/147)

**Comment by jwhitlock** [comment]
I don't believe we use the language features of [mod_negotiation](http://httpd.apache.org/docs/2.0/mod/mod_negotiation.html). The exception is that Apache may ship with localized versions of 404 pages and the "Welcome to Apache!" page, but we try to override this in Kuma.  I believe it is safe to ignore the ``AddLanguage`` directives, which I've only found in system-provided Apache config files.
