### ISSUE TITLE
decom unused Bedrock prod/stage ELBs

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#255]
delete `www-mozilla.org` and `www-allizom-org` ELBs in `eu-west-1` and `us-west-1`, as a wildcard DNS record handles traffic instead:

- [x] allizom.org
- [ ] mozilla.org

**Comment by jgmize** [comment]
The allizom.org ELB had a wildcard cert and was still in use by other "staging" sites, which were broken by this change until I created new "wildcard-allizom-org" ELBs and updated all the DNS entries/traffic policies to point to the new ELBs.  There was also an intermediate DNS entry on the www.allizom.org cloudflare backend that needed to be updated as well. Let's go over these in the morning and figure out the best way to document these dependencies.

**Comment by metadave** [comment]
see also: https://github.com/mozmar/infra/issues/178

**Comment by metadave** [comment]
leaving current ELB's as is, however we'll need MozMEAO DNS [documentation](https://github.com/mozmar/infra/issues/273).
