### ISSUE TITLE
status.mozmar.org troubleshooting and docs

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#264]
The following alerts were reported in Slack:

https://deadmanssnitch.com/snitches/b6a8280917
https://deadmanssnitch.com/snitches/3ea402d1d7

We're unsure where to go look for logs. Can you look into it and perhaps update the docs on where to look so we can easily troubleshoot next time?

**Comment by glogiotatidis** [comment]
status is documented in mana https://mana.mozilla.org/wiki/display/EN/status.mozmar.org, including the update produce and where to look for logs. Is that what you're looking for @metadave ?

**Comment by metadave** [comment]
👍 , thanks @glogiotatidis
