### ISSUE TITLE
convert MDN robots.txt to a Django view [tracking]

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#267]
This issue is for tracking the MDN upstream [bug 1367782](https://bugzilla.mozilla.org/show_bug.cgi?id=1367782).

See also: https://github.com/mozmar/infra/issues/217

**Comment by jwhitlock** [comment]
I can do this. I think it's a Django view that defaults to the restrictive robots.txt, but an env-backed setting can turn on the "permissive" robots.txt used in prod. ``ALLOW_ROBOTS``? We can work w/ webops to manage the transition from Apache in SCL3.

**Comment by jwhitlock** [comment]
https://github.com/mozilla/kuma/pull/4273 merged. It should remain unused in SCL3, where Apache will serve the request first.

**Comment by metadave** [comment]
thanks @jwhitlock!
