### ISSUE TITLE
migrate surveillance.m.o to K8s

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#269]

**Comment by jgmize** [comment]
surveillance.mozilla.org is now running in the virginia k8s cluster. @metadave and I paired on the steps below:

- removed http->https redirect from nginx config, as this is now handled by separate service in k8s: https://github.com/mozilla/surveillance.mozilla.org/commit/03ab7a0e2545377728bf215eabb0cb55a87f6c75
- built new image based on above commit and pushed to https://quay.io/repository/mozmar/surveillance?namespace=mozmar&tab=tags
- created surveillance-prod namespace: `kubectl create ns surveillance-prod`
- created pod in namespace based on above image: `kubectl run surveillance-prod --image=quay.io/mozmar/surveillance:03ab7a0 -n surveillance-prod`
- created nodeport service and ELB: https://github.com/mozmar/infra/pull/274
- Updated surveillance.moz.works record in route53 to point to new ELB
  - surveillance.mozilla.org is CNAMEd to surveillance.moz.works
