### ISSUE TITLE
Snippets + Careers Route53 + ELB checks to point to /healthz

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#309]
Snippets since commit  https://github.com/mozmar/snippets-service/commit/757555bcded2816e14f769df755d3abca6f83017 has a `/health` view for use with the healthchecks.

- [ ] Point ELB health checks to /healthz  
- [ ]  Point Route 53 health checks to /healthz  

I want to keep Synthetics checks as they are today, where they check another URL which returns snippets to make sure that we deliver content. `/healthz` are much faster and thus more appropriate to use in ELB and Route53 Health checks.

@metadave do we have some automation for Route53 Health Checks or can I manually edit them? Also for the ELBs I need to change the k8s service, correct? 

edit: clarified question to metadave

**Comment by metadave** [comment]
@glogiotatidis we've been doing Route 53 + health check changes manually for now, with the possibility of using K8s for DNS in the future. 

I have a pretty huge PR coming in the next few hours for the Frankfurt regions which includes a bunch of ELB terraform changes. 

It looks like the only change we need is to add:

        health_check_http_path       = "/healthz"

to https://github.com/mozmar/infra/blob/master/elbs/tf/all_elbs.tf#L65-L73

**Comment by glogiotatidis** [comment]
I left two comments in https://github.com/mozmar/infra/pull/311/files to point snippets and careers to the new healthcheck urls.

**Comment by glogiotatidis** [comment]
Manually changed the traffic policy health checks to point to /healthz/ for
  * snippets prod  (4 health checks)
  * snippets stage (2 health checks)
  * careers prod (4 health checks)

Aaaand done!
