### ISSUE TITLE
Evaluate www.mozilla.org CDN options

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#32]

**Comment by jgmize** [comment]
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-language

**Comment by jgmize** [comment]
https://docs.fastly.com/guides/vcl/accept-language%20header-vcl-features

**Comment by jgmize** [comment]
We decided to stick with the current CDN (Cloudflare) for www.mozilla.org in 2018.
