### ISSUE TITLE
Enable cron jobs

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#66]
Cron tasks aren't enabled by default w/ our kops install

https://github.com/kubernetes/kops/issues/618#issuecomment-281121955

**Comment by metadave** [comment]
Enable cron tasks w/
https://github.com/kubernetes/kops/issues/618

Apply changes with:
https://github.com/kubernetes/kops/blob/master/docs/changing_configuration.md
https://github.com/kubernetes/kops/blob/master/docs/terraform.md

**Comment by jgmize** [comment]
a docker GC job, as suggested in https://github.com/deis/workflow-e2e/issues/355, would be useful once this is complete

**Comment by jgmize** [comment]
@metadave https://github.com/mozmar/infra/projects/2#card-1879753 is in the complete column but this issue is still open and you expressed (understandable) hesitation to use the the cron job api for anything critical due to it still being in alpha. Do you think it would be appropriate for a GC job on the nodes, or would you prefer to use something else, as discussed in #196?

**Comment by metadave** [comment]
setting up K8s cron is documented [here](https://github.com/mozmar/infra/tree/master/k8s/install#enabling-k8s-cron), so this issue can be closed. 

Regarding the cron api, I feel as though a simple application of classic cron would work just fine, I don't think anything we do warrants the extra complexity of using custom Docker/K8s scheduling.

**Comment by jgmize** [comment]
Further evidence that you were right, @metadave: https://github.com/vdice/charts/blob/06c31c903509289eb164216d35d9220bfeddc959/stable/spotify-docker-gc/README.md#designevolution
