### ISSUE TITLE
MDN s3 bucket automation

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#69]
Using Terraform, create the following:

- 2 private S3 buckets
- 2 IAM security policies
- 2 IAM accounts using policy above

Notes:

- security policies will be created and managed in ee-infra-private
- the rest can go in this repo

**Comment by metadave** [comment]
https://github.com/mozmar/ee-infra-private/pull/69
https://github.com/mozmar/infra/pull/75

**Comment by jgmize** [comment]
fixed in #75
