### ISSUE TITLE
Slack Migration Tracking: Update Alerts & Docs

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#70]
Marketing slack is being merged into another slack instance:

https://docs.google.com/document/d/1mmOMZFPcDqXvpQz0LfNqd2Xmtsk6gkiiDyjeJ34TkhM/edit

We'll need to update appropriate alerts:
- New Relic
- AWS
- DataDog?

**Comment by bensternthal** [comment]
All dependencies are resolved. If we somehow missed something, we can re-open.
