### ISSUE TITLE
Install MySQL helm chart for MDN Maintenance Mode

### ISSUE THREAD

**Issue by metadave** [mozmar/infra#77]
See: https://github.com/kubernetes/charts/tree/master/stable/mysql

**Comment by jgmize** [comment]
Will need to fork chart and change https://github.com/kubernetes/charts/blob/master/stable/mysql/templates/deployment.yaml#L33 to point to the quay.io/mozmar/mdn-mysql image for custom collation.

**Comment by metadave** [comment]
https://github.com/mozmar/ee-infra-private/pull/70
https://github.com/mozmar/infra/pull/78

**Comment by metadave** [comment]
Closing in favor of https://github.com/mozmar/infra/issues/100
