### ISSUE TITLE
Switch NR alerts to mozilla slack instance

### ISSUE THREAD

**Issue by jgmize** [mozmar/infra#79]

**Comment by jgmize** [comment]
@pmac is investigating to see if this can be automated

**Comment by pmac** [comment]
failure. we apparently subscribe to "[synthetics lite](https://newrelic.com/synthetics/pricing)", but the API is only available to "synthetics pro" users. `<price-is-right-fail-trombone/>`

**Comment by jgmize** [comment]
subtask of #70

**Comment by bensternthal** [comment]
2 questions for yah here..

1. Under 'Alerts New' we have one notification channel that has 0 subscriptions, it uses #ee-alerts, am I clear to delete this?

2. Under 'APM Alerts' we have both the old alert and the new one. Am I clear to delete the old one?

Last night I saw the nr alerts being posted to both channels so I think this is working correctly.

**Comment by bensternthal** [comment]
@pmac i added your handle in an edit, so that might have not alerted you to the mention. Anyhew, see above.

**Comment by pmac** [comment]
> @pmac 2 questions for yah here..
> 
> 1. Under 'Alerts New' we have one notification channel that has 0 subscriptions, it uses #ee-alerts, am I clear to delete this?

Sounds right. Delete away 🗑 

> 2. Under 'APM Alerts' we have both the old alert and the new one. Am I clear to delete the old one?

Sounds right. Delete away 🗑 

> Last night I saw the nr alerts being posted to both channels so I think this is working correctly.

Agreed 👍

**Comment by bensternthal** [comment]
Done.
