### ISSUE TITLE
Move MDN configuration to mdn/infra

### ISSUE THREAD

**Issue by jwhitlock** [mozmar/infra#839]
With the transition of operations from MozMEAO, it makes sense to move the infrastructure configuration, etc. to a new repo.

Here's my plan:
1. Fork the repo to mdn/infra. Remove non-MDN references via PRs
2. Get deployments working on the new repo:
   - Update Jenkins configuration (Kuma and KumaScript) to point to the new repo (see below)
   - Update any other in-code references (deployment docs)
   - Update any MozMEAO references (not sure what these are, could use @metadave's help to identify anything that might break)
   - Run some successful deployments
3. Drop MDN references from this repo, migrate in-progress issues to new repo

The repository URL and paths in the repository are referenced in the Jenkins config push.groovy:

https://github.com/mozilla/kuma/blob/9db82a43bbe85fe28be7be9caf46974344735934/Jenkinsfiles/push.groovy#L10-L25

**Comment by metadave** [comment]
quay.io/mozmar/

The [RDS backup tool](https://github.com/mozmeao/infra/tree/master/tools/aws/rds_backup_tool) isn't in the apps/mdn tree, but you'll need that too.

**Comment by metadave** [comment]
After poking around for a few minutes, I don't see anything that would break. Jenkins and doc references cover most of the bases.

misc:

- I'm assuming that you're transitioning away from `quay.io/mozmar/`, will you move to Dockerhub instead?

- The [RDS backup tool](https://github.com/mozmeao/infra/tree/master/tools/aws/rds_backup_tool) isn't in the apps/mdn tree, but you'll need that too.

**Comment by metadave** [comment]
we were using quay.io awhile back for private images, but everything we have now is public. I figured you'd at least move off mozmar, but it's fine if you keep images there too. I have no preference between quay.io vs dockerhub.

**Comment by jwhitlock** [comment]
MDN dev tasks are in https://github.com/mdn/sprints/issues/148. It's not a complete list, just getting started.

Tracking docker image storage on https://github.com/mozilla-itcloud/mdn-migration-project/issues/15.

We're holding on the [rds_backup_tool](https://github.com/mdn/infra/tree/master/tools/aws/rds_backup_tool) and a lot of other stuff for now.
