### ISSUE TITLE
Datadog To New Slack

### ISSUE THREAD

**Issue by bensternthal** [mozmar/infra#86]
See https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=51610034

**Comment by bensternthal** [comment]
subtask of #70

**Comment by bensternthal** [comment]
@pmac i updated the webhook and changed the slack channel to meao-alerts on "Nearing SFDC API Call Limit"

However I could not find a way to manually trigger an alert to test, is this possible?

**Comment by pmac** [comment]
Great! Thanks. I think it should go to the channel if you make a comment on some data as well. That'd indicate it's functioning.

**Comment by pmac** [comment]
I'll give it a try.

**Comment by bensternthal** [comment]
Heh ok just tried, it works. OK so if the only slack alert for data dog is on the API call limit. This be done.
