### ISSUE TITLE
Route53 / Cloudwatch alarms SNS update to new Slack instance

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/infra#97]
The Route 53/ Cloudwatch alarms point to MozillaMarketing Slack. We need to update to Mozilla Slack

**Comment by jgmize** [comment]
See also #80

**Comment by jgmize** [comment]
Subtask of #70

**Comment by metadave** [comment]
The topic still shows `MozillaMarketing Slack`, but it's pointing at the new slack email that pmac emailed out.

**Comment by jgmize** [comment]
closing based on previous comment and IRC discussion
